apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-api
  namespace: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
      - name: predict
        image: 539825460310.dkr.ecr.ap-south-1.amazonaws.com/predict-api:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000

